write_story_idea_task:
  description: >
    Write a story idea with {genre} genre
  expected_output: >
    A story idea with {genre} genre. The idea should include characters, setting, plot, theme, point of view, tone and style
  agent: story_writer

review_story_idea_task:
  description: >
    Review the story idea and provide feedback on it.
  expected_output: >
    Rating of the story idea from 1 to 10. 1 being the worst and 10 being the best.
    Also provide constructive feedback on the story idea. Try to be as objective as possible.
    Present the feedback in a structured way, with sections for strengths and weaknesses.
  agent: story_reviewer

improve_story_idea_task:
  description: >
    Improve the story idea based on the feedback
  expected_output: >
    Then returns the improved story idea.
    As the original story idea, it should include characters, setting, plot, theme, point of view, tone and style.
    Add additional section that states how the story idea has been improved.
  agent: story_writer
